#20797377 Верстка нижней строки
frontend-park-mail-ru/2023_2_Vkladyshi pull request #1
Opened 2023-09-28 08:49 UTC by AlfaIV

https://aleksejy60.kaiten.ru/space/219541/card/20797377

2023-09-28 15:41 UTC, Kostich31 requested changes

2023-09-28 15:41 UTC, Kostich31 commented on src/public/components/footer/footer.css
> +.footer div {
В данном случае можно обойтись без использования селектора по html тегу, это не очень хорошая практика. Будет достаточно добавить стили на родительскую ноду, дальше они будут наследоваться во вложенных.

2023-09-28 15:41 UTC, Kostich31 commented on src/public/components/footer/footer.css
> +  width: var(--footer-text-width);
Не стоит хардкодить ширину элементов, лучше заранее закладывать адаптивность для разных экранов. Ты говорил, что нужно расположить логотип по центру экрана. Попробуй процентное отношение ширины для трех элементов внутри footer.
Для текста
`width:25%;
display:flex;
`
А для логотипа 50 процентов и позиционировать по центру. Также здесь нет смысла указывать высоту, она будет наследоваться от родителя и так.
https://habr.com/ru/articles/467049/ - про flex почитать советую.

2023-09-28 15:41 UTC, Kostich31 commented on src/public/components/footer/footer.hbs
> +</div>
Не забываем про пустую строку в конце файла.

2023-09-28 15:41 UTC, Kostich31 commented on src/public/components/footer/footer.hbs
> +<div class="footer">
Почему бы здесь сразу же не добавить вместо div-а footer.

2023-09-28 15:41 UTC, Kostich31 commented on src/public/index.css
> +  display: flex;
Почитай про reset.css. https://habr.com/ru/companies/otus/articles/580442/
В теге body не нужно указывать подобные стили.

2023-09-28 15:41 UTC, Kostich31 commented on src/public/index.css
> +  height: 2000px;
Также непонятно откуда взятая константа, но полагаю, что это для теста

2023-09-28 15:41 UTC, Kostich31 commented on src/public/index.html
> +    <div id="contentBlock">
Данный div должен находиться внутри #root. Как и все остальные блоки, в том числе footer.

2023-09-28 19:09 UTC, AlfaIV commented on src/package.json
> +{
Я просто вытянул все из src. Убрал папку src.

2023-09-28 19:11 UTC, AlfaIV commented on src/public/components/contentBlock/contentBlock.css
> +  width: 1222px;
Я просто взял из макета....
Типа ширина рабочей области.

2023-09-28 19:18 UTC, AlfaIV commented on src/public/components/footer/footer.css
> +  gap: 400px;
Убрал лишнее. Но right = 0 оставил. Чтобы footer был растянут на всю ширину экрана. Этот footer еще Андрей внесет исправления своим комитами.

2023-09-28 19:21 UTC, AlfaIV commented on src/public/index.html
> +    <div id="contentBlock">
Убрал в root.

2023-09-28 19:22 UTC, AlfaIV commented on src/public/components/footer/footer.hbs
> +<div class="footer">
Логично. Поменял на footer.

2023-09-28 19:24 UTC, AlfaIV commented on src/public/index.css
> +  height: 2000px;
Это просто заглушка для красоты, чтобы страницу можно было полистать вверх-вниз. Уберу по мере заполнения страницы контентом.

2023-09-28 19:25 UTC, AlfaIV commented on src/public/components/footer/footer.hbs
> +</div>
Её и меня форматтер срезает. Это нужно его настраивать. Я даже не могу её добавить....

2023-09-28 19:33 UTC, AlfaIV commented on src/public/components/footer/footer.css
> +.footer div {
Если убрать div и оставить эти свойства только на .footer, то наследуется и свойство прозрачности(opacity). И footer станет полупрозрачным, а должен быть черным.

2023-09-28 19:43 UTC, Kostich31 commented on src/public/components/footer/footer.css
> +.footer div {
Может быть тогда перенести это свойство на те элементы, которые должны быть полупрозрачными?

2023-09-28 19:44 UTC, Kostich31 commented on src/public/components/footer/footer.css
> +  gap: 400px;
width:100% и так растянет блок на всю ширину

2023-09-29 06:50 UTC, AlfaIV commented on src/public/components/footer/footer.css
> +  gap: 400px;
Вроде все поправил.

2023-09-29 06:50 UTC, AlfaIV commented on src/public/components/footer/footer.css
> +  width: var(--footer-text-width);
Так действительно удобнее.

2023-09-29 06:53 UTC, Kostich31 commented on src/public/components/footer/footer.css
> +  gap: 400px;
Жду новых коммитов)
Не закрывай тред, я сам его закрою

2023-09-29 06:53 UTC, AlfaIV commented on src/public/components/footer/footer.css
> +.footer div {
Настройки текста перекинул в .footer. А opacity накидал в соответствующие блоки.

2023-09-29 06:58 UTC, AlfaIV commented on src/public/index.css
> +  display: flex;
Про reset.css, если честно, не понял до конца.  В статье куча разных css конфигов. В ** Reboot.css ** вроде в body все настройки задают, как и у меня.

``` CSS
body {
  margin: 0; /* 1 */
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  font-size: 1rem;
  font-weight: normal;
  line-height: 1.5;
  color: #212529;
  text-align: left; /* 3 */
  background-color: #fff; /* 2 */
}
```

В итоге переместил все в html.

2023-09-29 07:04 UTC, AlfaIV commented
Коммит отправил. Про тред понял, открыл.
Мне просто, так удобно я исправляю и пишу сразу комментарии, чтобы потом не забыть, что хотел сказать. И закрывать треды в которых вопросов вроде не осталось.

2023-09-29 07:15 UTC, Kostich31 commented on .gitignore
> +src/node_modules/
Забыл изменить путь для игнорирования папки модулей

2023-09-29 07:34 UTC, Kostich31 commented on src/public/index.css
> +  display: flex;
Сброс стилей обычно применяют не только к body, но и к остальным тегам, чтобы в разных браузерах сайт выглядел одинаково, так как каждый браузер имеет свои собственные стили по умолчанию. В целом пока можно оставить и так.

2023-09-29 07:39 UTC, AlfaIV commented on .gitignore
> +src/node_modules/
Исправил

2023-09-29 07:49 UTC, Kostich31 commented on .gitignore
> +src/node_modules/
Кажется, что нет. Обычно IDE-шка затемняет те директории или файлы, которые затронуты .gitignore.

2023-09-29 08:01 UTC, AlfaIV commented on .gitignore
> +src/node_modules/
Я удалил node_module из кеша гита. Если я правильно понял проблему.
Просто, gitignore не удаляет файлы, а просто препятствует их дальнейшему добавлению. А я в предыдущем коммите уже добавил node_module, поэтому теперь приходиться руками убирать его.

2023-09-29 08:05 UTC, Kostich31 commented
Все ок. Предлагаю склеить твои коммиты в один с понятным сообщением о том, что было сделано в задаче.

2023-09-29 15:55 UTC, merged