new branch
frontend-park-mail-ru/2023_2_Vkladyshi pull request #14
Opened 2023-10-14 11:38 UTC by Gokert

2023-10-14 11:39 UTC, Gokert commented
![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/74991205/6507c9c6-f876-436a-867f-f42a81c69e70)
Это сделаю чуть позже

2023-10-14 12:09 UTC, Kostich31 commented
![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/29610387/063803db-cabb-450c-ac79-2ab0a3ac1291)
Может быть задать минимальную фиксированную высоту экрана для контента и придумать какой-нибудь placeholder для той ситуации, если фильмов не будет в подборке? А то выглядит как-то не очень.
Высоту можно в зависимости от высоты пользовательского экрана задать

2023-10-14 12:10 UTC, Kostich31 commented
Как-то странно прыгает интерфейс при открытии модалки + стрелки на регистрации/авторизации очень маленькие, как мне кажется, я со второго раза смог тыкнуть на них. 
И почему нельзя закрыть модалку, нажав на область вне ее? Это очень ожидаемое поведение, его нужно добавить.

2023-10-15 11:17 UTC, Kostich31 requested changes

2023-10-15 11:17 UTC, Kostich31 commented on public/components/ContentBlock/contentBlock.css
> +  min-height: 400px;
может задать зависимость от размера экрана пользователя? Например, от видимой области. Потому что на мобильном устройстве эти 400px могут быть слишком велики

2023-10-15 14:18 UTC, Gokert commented on public/components/ContentBlock/contentBlock.css
> +  min-height: 400px;
![изображение](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/74991205/c3fa9416-0412-467c-8aa5-f16141e59867)
Ну, как-то так у меня выглядит

2023-10-15 14:19 UTC, Gokert commented on public/components/ContentBlock/contentBlock.css
> +  min-height: 400px;
Нужно же сделать небольшое белое пространство под текстом ?

2023-10-15 15:41 UTC, Kostich31 commented on public/components/ContentBlock/contentBlock.css
> +  min-height: 400px;
![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/29610387/8bd31aea-c85b-4f87-a92d-7efaa7e48072)
ну вот я поставил 100vh, можно поставить чуть меньше, например, 85

2023-10-15 23:20 UTC, Kostich31 requested changes

2023-10-15 23:20 UTC, Kostich31 commented on public/views/SignupPage/SignupPage.js
> +        returnError(errorInputs.EmailNoValid, 'errorStringSignup');
Как-то много дублирования одинакового текста, может в константу вынести?

2023-10-17 18:09 UTC, merged