#23794342 Верстка страницы актера
frontend-park-mail-ru/2023_2_Vkladyshi pull request #19
Opened 2023-10-31 20:54 UTC by AlfaIV

[Ссылка на Kaiten](https://aleksejy60.kaiten.ru/space/219541/card/23794342)

2023-11-01 06:30 UTC, Kostich31 requested changes

2023-11-01 06:30 UTC, Kostich31 commented on public/utils/config.ts
> +export const LkStar = new LikeStar(ROOT)
likeStar?

2023-11-01 06:30 UTC, Kostich31 commented on public/utils/getCollection.ts
> +export const getActorDescrition = () => {
А почему бы не вынести эти данные на ваш моковый бэкенд?

2023-11-01 06:30 UTC, Kostich31 commented on public/views/FilmSelectionPage/FilmSelectionPage.ts
> +    return store
Рендер не должен быть асинхронным, если тебе нужно определенные данные получить в компонент, то либо запрашивай и передавай их до рендера, либо в  componentDidMount делай запрос и запускай перерендер.
Думаю, в данном случае лучше первый вариант

2023-11-01 06:30 UTC, Kostich31 commented on public/views/SelectCollectionPage/SelectCollectionPage.ts
> +      path: `/api/v1/films?collection_id=${this.state.dataSection}`,
Почему через роутер идет навигация на вашу АПИ?

2023-11-02 19:26 UTC, Gokert commented on public/views/SelectCollectionPage/SelectCollectionPage.ts
> +      path: `/api/v1/films?collection_id=${this.state.dataSection}`,
изменил

2023-11-03 10:44 UTC, Kostich31 requested changes

2023-11-03 10:44 UTC, Kostich31 commented on public/views/FilmSelectionPage/FilmSelectionPage.ts
> +  async render (isNotMain) {
Все еще функция render содержит асинхронные вызовы. render занимается тем, что изменяет dom-элементы, внутри этой функции не должно быть асинхронных запросов. По-хорошему, запрос нужно делать снаружи этой страницы, либо внутри, например, в componentDidMount, который изменит store, а затем за стором произойдет перерендер

2023-11-03 13:19 UTC, merged