#24027563 Верстка страницы фильма
frontend-park-mail-ru/2023_2_Vkladyshi pull request #22
Opened 2023-11-04 19:57 UTC by AlfaIV

Сделал компоненты к странице фильма и пользователя. И накидал поверхностного странички.

2023-11-04 21:05 UTC, Kostich31 requested changes

2023-11-04 21:05 UTC, Kostich31 commented on public/components/Button&Form/button&form.css
> +.button {
А что это за компонент с таким странным наименованием?

2023-11-04 21:05 UTC, Kostich31 commented on public/components/ChangeUserData/changeUserData.ts
> +import { Component } from '@components/component';
Судя по функционалу, это компонент формы для изменения данных. Почему бы не назвать тогда компонент UserDataForm, например. Потому что данное наименование больше напоминает по семантике название функции какой-то, а не компонента интерфейса. Лучше переименовать.

2023-11-04 21:05 UTC, Kostich31 commented on public/views/FilmPage/FilmPage.ts
> +    // fix it
Советую добавлять комментарии в таком формате: //TODO нужно исправить в будущем в тех местах, который нужно исправить в будущем.

2023-11-05 09:43 UTC, AlfaIV commented on public/components/Button&Form/button&form.css
> +.button {
Я начал выносить какие-то общие свойства компонентов в отдельный компонент. Так как все кнопки визуально похожи(типа общий стиль). Я вынес свойство фигуры кнопки(скругления и отступы) в отдельный компонент.

2023-11-05 09:43 UTC, AlfaIV commented on public/views/FilmPage/FilmPage.ts
> +    // fix it
Понял

2023-11-05 09:44 UTC, AlfaIV commented on public/components/ChangeUserData/changeUserData.ts
> +import { Component } from '@components/component';
Ну можно, в принципе

2023-11-05 09:49 UTC, Kostich31 commented on public/components/Button&Form/button&form.css
> +.button {
Так почему бы тогда не сделать просто директорию с названием Button, где будет шаблон компонента, общий файл стилей и класс, и файл с общей логикой работы кнопки (подписка на нажатия, текст для кнопки)

2023-11-05 09:53 UTC, Kostich31 commented on public/components/Button&Form/button&form.css
> +.button {
В целом это можно сделать и потом, но название поменять точно нужно. Лучше просто назвать Button

2023-11-07 13:21 UTC, Kostich31 requested changes

2023-11-07 13:21 UTC, Kostich31 commented on public/components/Button&Form/button&form.css
> +.button {
С этим моментом будешь что-то менять? Не очень понятно, почему этот код лежит не внутри button.css.

2023-11-07 13:21 UTC, Kostich31 commented on public/components/ChangeUserData/changeUserData.ts
> +import { Component } from '@components/component';
Про это тоже напоминаю

2023-11-07 13:21 UTC, Kostich31 commented on public/components/RewiewForm/rewiewForm.hbs
> +<div class='rewiewForm'>
Наверное, review все же

2023-11-09 13:05 UTC, closed without merging