Страницы фильма настроек актёра
frontend-park-mail-ru/2023_2_Vkladyshi pull request #23
Opened 2023-11-07 08:12 UTC by Gokert

2023-11-07 13:19 UTC, Kostich31 requested changes

2023-11-07 13:19 UTC, Kostich31 commented on public/router/router.ts
> +        { path: path, props: props },
Можно сократить до {path, props}

2023-11-07 13:19 UTC, Kostich31 commented on public/views/FilmPage/FilmPage.ts
> +    const popupEvent = (event) => {
Может быть это вынести в отдельный метод класса, слишком большая функция получилась

2023-11-07 13:19 UTC, Kostich31 commented on public/views/FilmPage/FilmPage.ts
> +      actors = filmInfo['actors'];
А почему бы не обращаться через точку, filmInfo.smth

2023-11-07 13:19 UTC, Kostich31 commented on public/views/FilmPage/FilmPage.ts
> +    popup?.addEventListener('click', this.popupEvent);
А почему на unmount происходит подписка на попап?
Может быть здесь removeEventListener?

2023-11-07 13:19 UTC, Kostich31 commented on public/views/userPage/userPage.ts
> +    const handleSubmit = (event) => {
Тоже отдельным методом класса можно сделать. И внутрь передавать нужные ноды

2023-11-09 18:32 UTC, Kostich31 requested changes

2023-11-09 18:32 UTC, Kostich31 commented on public/views/FilmPage/FilmPage.ts
> +import { response } from 'express';
А что это за response?

2023-11-10 11:42 UTC, Gokert commented on public/views/FilmPage/FilmPage.ts
> +import { response } from 'express';
Моя IDE случайно добавила

2023-11-10 12:48 UTC, Kostich31 requested changes

2023-11-10 12:48 UTC, Kostich31 commented on public/components/SelectCollection/contentBlockElement.css
> +.\selectCollection-frame-lists {
А это что за обратный слэш?

2023-11-13 10:35 UTC, merged