#20744879 Верстка верхней строки
frontend-park-mail-ru/2023_2_Vkladyshi pull request #3
Opened 2023-09-29 18:23 UTC by Gokert

2023-09-29 18:30 UTC, Kostich31 requested changes

2023-09-29 18:30 UTC, Kostich31 commented on public/components/contentBlock/contentBlock.css
> +  max-width: 1222px;
Почему такое ограничение?

2023-09-29 18:30 UTC, Kostich31 commented on public/index.html
>        <div id="contentBlock">
А почему контентный блок уже есть в верстке, а не добавляется через js в `root`?

2023-09-29 18:30 UTC, Kostich31 commented on public/modules/ajax.js
> +(function() {
Вам же на лекции рассказывали про ES6 модули, зачем использовать IIFE, если можно создать класс и в нем описать все нужные методы для запросов и экспортировать его.

2023-09-29 18:30 UTC, Kostich31 commented on public/modules/ajax.js
> +        _ajax({method, url, body = null, callback = noop}) {
Используйте современные способы для запросов.
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

https://learn.javascript.ru/fetch

2023-09-29 22:08 UTC, Gokert commented on public/components/contentBlock/contentBlock.css
> +  max-width: 1222px;
Исправил

2023-09-29 22:08 UTC, Gokert commented on public/index.html
>        <div id="contentBlock">
Убрал

2023-09-29 22:09 UTC, Gokert commented on public/modules/ajax.js
> +(function() {
Изменил

2023-09-29 22:09 UTC, Gokert commented on public/modules/ajax.js
> +        _ajax({method, url, body = null, callback = noop}) {
сделал через [Fetch_API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

2023-09-30 06:24 UTC, Kostich31 commented
Все ок. Предлагаю склеить твои коммиты в один с понятным сообщением о том, что было сделано в задаче.
https://htmlacademy.ru/blog/git/how-to-squash-commits-and-why-it-is-needed

2023-09-30 15:25 UTC, Gokert commented
последнее изменение это #21141844_Вёрстка_страницы_регистрации

2023-09-30 15:26 UTC, Kostich31 requested changes

2023-09-30 15:26 UTC, Kostich31 commented on public/components/login/login.css
> +#login_box {
Лучше использовать классы вместо id в качестве селектора.

2023-09-30 15:26 UTC, Kostich31 commented on public/components/login/login.css
> +#login_form input {
Плохая практика добавлять стили через селектор html-тега, так как это может усложнить дальнейшую разработку и поддержку стилей. Достаточно будет просто добавить класс, например, loginInput, назначить его на нужный элемент. Это будет более читаемо и поддерживаемо.
В особенности, если внутри формы для разных инпутов нужны будут разные стили.

Соответственно это замечание на все похожие случаи ниже распространяется.

2023-09-30 15:26 UTC, Kostich31 commented on public/components/login/login.mjs
> +                url: '/login',
Советую заранее начать выносить все подобные константы в отдельные файлы, откуда их будет удобнее импортировать и использовать в разных частях проекта. Т.е. все url-ы, значения кодов статуса ответа и т.п.

2023-09-30 15:26 UTC, Kostich31 commented on public/modules/ajax.js
> +        return await fetch(params.url, {
Зачем одновременно использовать await и then? Обычно используется либо одно, либо другое. В данном случае, если хочешь использовать await, то логичней будет сделать так:


```
const response = await fetch(...);
return {
response,
status: response.status
}
```

+ здесь не хватает проверки на статус ответа от сервера

2023-09-30 18:43 UTC, Gokert commented on public/components/login/login.mjs
> +                url: '/login',
Вынес константы в отдельный файл

2023-09-30 18:43 UTC, Gokert commented on public/components/login/login.css
> +#login_form input {
убрал все айдишники

2023-09-30 18:43 UTC, Gokert commented on public/components/login/login.css
> +#login_box {
исправил

2023-09-30 18:43 UTC, Gokert commented on public/modules/ajax.js
> +        return await fetch(params.url, {
изменил

2023-09-30 18:53 UTC, Kostich31 commented
Все ок. Также склей коммиты и запушь в dev

2023-09-30 18:58 UTC, merged