#25317109 Календарь релизов
frontend-park-mail-ru/2023_2_Vkladyshi pull request #31
Opened 2023-11-26 18:51 UTC by AlfaIV

[Ссылка на Kaiten](https://aleksejy60.kaiten.ru/space/219541/card/25317109)

2023-11-26 18:52 UTC, AlfaIV commented
Пока так. Буду еще моменты дорабатывать, как руки дойдут. В карточке Kaiten накидал дальнейшие моменты для доработки.

2023-11-27 18:43 UTC, Kostich31 requested changes

2023-11-27 18:43 UTC, Kostich31 commented on public/components/Calendar/calendar.hbs
> +    {{! Не забыть навестить каласс текущий день }}
А что здесь должно быть?

2023-11-27 18:43 UTC, Kostich31 commented on public/components/Calendar/calendar.ts
> +    // const days = {
Может тогда вообще удалить эти строки, раз на мок-бэкенд добавил данные?

2023-11-28 19:18 UTC, merged