added registration and validation
frontend-park-mail-ru/2023_2_Vkladyshi pull request #4
Opened 2023-10-01 10:52 UTC by Gokert

2023-10-01 10:59 UTC, Kostich31 requested changes

2023-10-01 10:59 UTC, Kostich31 commented on public/components/signup/signup.mjs
> +                    case response_statuses.success:
camelCase.
По коду везде посмотри и исправь

2023-10-01 10:59 UTC, Kostich31 commented on public/components/signup/signup.mjs
> +                returnError(loginBox, "Пароли не совпадают")
Может быть подобные тексты ошибок вынести также в константы?

2023-10-01 10:59 UTC, Kostich31 commented on public/index.css
>  .contentBlock > p {
Зачем для параграфов высоты в 2000px?

2023-10-01 11:35 UTC, Kostich31 commented
Я решил проект запустить и посмотреть.
1. Почему нет футера и контентной части при первом заходе на страницу? Причем, если авторизоваться, затем удалить куку и перезагрузить страницу, то контентная часть и футер остаются.
2. Почему ширина контентной области не равне ширине экрана?
![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/29610387/4405749a-d28c-41e6-b1d1-a71a71468054)

3. При переходе из модалки авторизации в модалку регистрации не могу вернуться обратно.
4. После авторизации я не могу разлогиниться.
5. После авторизации удалил куку, перезагрузил страницу и кнопка "Войти" стала неактивной.
6. Не знаю как, но несколькими кликами по кнопке войти создал несколько модальных окон.

2023-10-01 11:37 UTC, Kostich31 requested changes

2023-10-01 11:37 UTC, Kostich31 commented on public/index.js
> +        goToPage(e.target);
Если кликнуть ровно на иконку, либо на текст "Войти", то показ модалки не сработает, так как data атрибут находится на родителе. Нужно это учесть и доставить дата-атрибут корректно

2023-10-01 11:40 UTC, Kostich31 requested changes

2023-10-01 11:40 UTC, Kostich31 commented on public/components/header/header.hbs
> +            <span class="loginText">{{ login.name }}</span>
Может быть добавить для кнопок в хэдере состояния cursor:pointer, чтобы было понятней, что на кнопки можно нажимать

2023-10-01 12:35 UTC, Kostich31 requested changes

2023-10-01 12:35 UTC, Kostich31 commented on .eslintrc.js
> +        "react"
А почему используете плагин для реакта, если он не используется в проекте?

2023-10-01 12:35 UTC, Kostich31 commented on .eslintrc.js
> +        "react"
+ я бы еще добавил stylelint для css файлов

2023-10-01 16:02 UTC, Kostich31 requested changes

2023-10-01 16:02 UTC, Kostich31 commented on package.json
> +    "compile:templates": "handlebars public/components/contentBlock/contentBlock.hbs -f public/components/contentBlock/contentBlock.precompiled.js && handlebars public/components/header/header.hbs -f
Нет желания написать скрипт, который будет проходиться по директории и собирать все файлы для компиляции? Если нет, то тред закрыть можете.

2023-10-01 20:56 UTC, Gokert commented on public/index.js
> +        goToPage(e.target);
Исправил

2023-10-01 20:56 UTC, Gokert commented on public/index.css
>  .contentBlock > p {
Это временно, там вообще контент должен быть вместо него

2023-10-01 20:57 UTC, Gokert commented on public/components/signup/signup.mjs
> +                returnError(loginBox, "Пароли не совпадают")
Вынес

2023-10-01 20:57 UTC, Gokert commented on public/components/signup/signup.mjs
> +                    case response_statuses.success:
Сделал

2023-10-01 21:06 UTC, Gokert commented on .eslintrc.js
> +        "react"
добавил stylelint

2023-10-01 21:07 UTC, Gokert commented on package.json
> +    "compile:templates": "handlebars public/components/contentBlock/contentBlock.hbs -f public/components/contentBlock/contentBlock.precompiled.js && handlebars public/components/header/header.hbs -f
Особого делания нету )

2023-10-02 05:44 UTC, Kostich31 requested changes

2023-10-02 05:44 UTC, Kostich31 commented on public/modules/validate.js
> +export function validateEmail(email) {
А валидация для пароля?

2023-10-02 05:47 UTC, Kostich31 requested changes

2023-10-02 05:47 UTC, Kostich31 commented on public/index.js
> +            if (responseStatuses.success) {
А почему здесь не исправил проверку условия?
И в целом мы на звонке говорили, что можно вынести логику из компонентов в отдельный модуль для каждой страницы. Это планируется в данном МРе?

2023-10-02 15:21 UTC, Gokert commented on public/index.js
> +            if (responseStatuses.success) {
Да, забыл проверку изменить.

2023-10-02 15:43 UTC, Kostich31 requested changes

2023-10-02 15:43 UTC, Kostich31 commented on public/modules/checkAuthorized.js
> +    const ajax = new Ajax();
Может быть избавиться от класса Ajax и разделить его на отдельные методы для работы с сетью, так как здесь по сути нет необходимости создавать экземпляр класса Ajax, у нас нет внутреннего состояния у этого объекта. Кажется, что достаточно будет просто импортировать отдельные нужные методы в соответствующие файлы и там использовать.

2023-10-02 16:35 UTC, Gokert commented on public/components/contentBlock/contentBlock.mjs
> +    #footer
Убрал #footer. Хотя в рендеринге я сделал проверку наличия футера, чтобы его добавить в случае отсуствия

2023-10-02 16:43 UTC, Kostich31 commented on public/components/contentBlock/contentBlock.mjs
> +    #footer
Этим не нужно заниматься внутри контентного блока в любом случае. Контентный блок занимается отрисовкой данных в рамках своей логики, все, что вокруг него, в идеале не должно быть затронуто.

2023-10-02 17:08 UTC, Gokert commented on public/components/contentBlock/contentBlock.mjs
> +    #footer
Переделаю в следующем ПР

2023-10-02 17:09 UTC, Kostich31 requested changes

2023-10-02 17:09 UTC, Kostich31 commented on public/components/signup/signup.mjs
> +import {post} from "../../modules/postResponse.js";
Один файл, в нем несколько функций, экспортируемых наружу. В данном случае будут get и post

2023-10-02 17:40 UTC, Gokert commented on public/components/signup/signup.mjs
> +import {post} from "../../modules/postResponse.js";
Сделал

2023-10-02 17:49 UTC, Kostich31 commented
Все ок. Можешь клеить и пушить

2023-10-02 17:52 UTC, merged