added logout
frontend-park-mail-ru/2023_2_Vkladyshi pull request #6
Opened 2023-10-02 23:32 UTC by Gokert

2023-10-03 05:15 UTC, Kostich31 requested changes

2023-10-03 05:15 UTC, Kostich31 commented on public/components/header/header.css
> +a {
Используй классы вместо селекторов тега, чтобы добавить стили элементам

2023-10-03 05:15 UTC, Kostich31 commented on public/index.js
> +if (document.cookie) {
Это какая-то временная проверка, пока нет бэкенда?
Если да, то лучше научи ноду выставлять куки для авторизации и проверяй авторизацию через запрос на определенную ручку при первом заходе пользователя на сайт. Легче будет с бэкендом потом интегрироваться

2023-10-03 05:16 UTC, Kostich31 requested changes

2023-10-03 05:16 UTC, Kostich31 commented on public/modules/config.js
>      basket: "/basket",
Что отдают ручки basket, content и selection?

2023-10-03 09:35 UTC, Kostich31 commented
Запустил проект, небольшие замечания есть:
![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/29610387/324e6bf5-1b43-4cb6-b9f6-ac5a037691c6)
1. Плейсхолдеры на русском должны быть
2. Кнопку "Вы еще не зарегистрированы" по центру поместить было бы неплохо.
![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/29610387/68f01251-98b4-4414-909e-468aadea0e44)
3. Надпись выходит за пределы блока
4. Не очень круто, когда каждая последующая ошибка о неправильном формате пароля появляется после исправления предыдущий. Т.е. я минимум 3 раза пытался зарегистрироваться, пока не сформировал пароль в нужном виде. Может быть лучше сразу же писать, какие требования к паролю предъявляются?
5. Ошибка 400. Не передается почта пользователя.
![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/29610387/d7a32915-a93f-4cb3-be30-4b8a7b492be2)

6. Какие-то слишком маленькие по высоте инпуты, + они почему-то разной ширины, выглядит немного странно
7.  Что-то слишком низкое качество у картинки. Может быть использовать svg вместо png?

![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/29610387/7ab4c066-cc59-48ed-acc1-0068844057f3)

![image](https://github.com/frontend-park-mail-ru/2023_2_Vkladyshi/assets/29610387/6d591bfc-d28c-46fe-94e5-f670d5bbdaa5)

2023-10-03 13:18 UTC, Gokert commented on public/components/header/header.css
> +a {
Сделал

2023-10-03 13:19 UTC, Gokert commented on public/index.js
> +if (document.cookie) {
Мне так бэкендиры сказали

2023-10-03 14:12 UTC, Gokert commented on public/index.js
> +if (document.cookie) {
Ну, у нас по сути только одна сессионная кука, поэтому я так сделал. Однако в случае установки нескольких кук , то этой проверки будет не достаточно. Ты мне предлагаешь удалять конкретную ? Только сессионную ?

2023-10-03 14:12 UTC, Kostich31 commented
А как проверить создание аккаунта?

2023-10-03 14:18 UTC, Gokert commented
Не понял. Типа что аккаунт был создан ?

2023-10-03 14:29 UTC, Kostich31 commented
> Не понял. Типа что аккаунт был создан ?

Нет, я не могу локально проверить процесс создания аккаунта. ошибка 400

2023-10-04 05:17 UTC, Kostich31 requested changes

2023-10-04 05:17 UTC, Kostich31 commented on public/modules/logout.js
> +    document.cookie = "session_id=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
а что эта строка делает?

2023-10-04 05:18 UTC, Kostich31 requested changes

2023-10-04 05:18 UTC, Kostich31 commented on public/index.js
> +if (document.cookie) {
Да

2023-10-04 05:21 UTC, Gokert commented on public/modules/logout.js
> +    document.cookie = "session_id=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
разве не для того чтобы сессионное куки удалить ? Ранее я все куки удалял

2023-10-04 05:22 UTC, Gokert commented
Да? Что ты имеешь в виду ?

2023-10-04 12:45 UTC, Kostich31 requested changes

2023-10-04 12:45 UTC, Kostich31 commented on public/components/selectCollection/contentBlockElement.css
> +  /* position: absolute;
А эти комментарии?

2023-10-04 13:01 UTC, Gokert commented on public/components/selectCollection/contentBlockElement.css
> +  /* position: absolute;
Убрал

2023-10-04 13:14 UTC, merged